const {chromium}=require('../tmp/ui-check/node_modules/playwright');
const assert=require('node:assert/strict');
const base=process.env.TEST_BASE_URL||'http://127.0.0.1:8149/';
(async()=>{
  const browser=await chromium.launch({channel:'chrome',args:['--enable-unsafe-swiftshader']});
  try{
    const context=await browser.newContext({viewport:{width:1366,height:768}}),page=await context.newPage();
    const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.addInitScript(()=>{window.EstudiemosAccount={whenReady:async()=>{},getClient:()=>null,getUser:()=>null,getSession:()=>null};});
    await page.route('**/api/**',r=>r.fulfill({json:{enabled:false}}));
    await page.goto(base,{waitUntil:'networkidle'});
    await page.locator('[data-home-customize]').click();
    const tool=key=>page.locator(`[data-home-space=${key}]`);
    const before=await tool('focus').boundingBox(),progress=await tool('progress').boundingBox();
    const resize=await page.locator('[data-home-resize=focus]').boundingBox();
    await page.mouse.move(resize.x+14,resize.y+14);await page.mouse.down();
    await page.mouse.move(resize.x-86,resize.y-56,{steps:6});await page.mouse.up();
    const smaller=await tool('focus').boundingBox();assert.ok(Math.abs(smaller.width-before.width+100)<2);
    assert.deepEqual(await tool('progress').boundingBox(),progress,'neighbors do not fill the gap');
    const handle=await page.locator('[data-home-move=focus]').boundingBox();
    await page.mouse.move(handle.x+handle.width/2,handle.y+handle.height/2);await page.mouse.down();
    await page.mouse.move(handle.x+handle.width/2+50,handle.y+handle.height/2+30,{steps:6});
    const moving=await tool('focus').boundingBox();assert.ok(Math.abs(moving.x-before.x-50)<2,'tool follows cursor');
    await page.mouse.up();
    await page.waitForTimeout(300);
    const after=await tool('focus').boundingBox();assert.ok(Math.abs(after.x-before.x-50)<2,'free position persists without swapping');
    await page.reload({waitUntil:'networkidle'});assert.ok(Math.abs((await tool('focus').boundingBox()).x-after.x)<2,'reorder persists');
    await page.locator('[data-home-customize]').click();
    const resizer=page.locator('[data-home-resize=focus]');
    const initial=await tool('focus').boundingBox();
    await resizer.press('Shift+ArrowRight');
    const resized=await tool('focus').boundingBox();assert.ok(Math.abs(resized.width-initial.width-1)<1,'one-pixel keyboard resizing');
    const saved=await page.evaluate(()=>localStorage.getItem('estudiemos_home_layout_local'));
    const next=await resizer.boundingBox();await page.mouse.move(next.x+14,next.y+14);await page.mouse.down();
    await page.mouse.move(next.x+90,next.y+next.height/2,{steps:4});await page.keyboard.press('Escape');await page.mouse.up();
    assert.equal(await page.evaluate(()=>localStorage.getItem('estudiemos_home_layout_local')),saved,'Escape rolls back without saving');
    await page.waitForTimeout(300);
    assert.ok(await page.locator('.workspace-page').evaluate(n=>n.scrollHeight<=n.clientHeight+1));
    assert.deepEqual(errors,[]);console.log('PASS movement, continuous resize, persistence and cancellation');
  }finally{await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
